language: node_js

node_js:
  - "11"

install:
  - npm install

script:
  - npm run build

after_success:
  - rm -rf .git
  - git clone https://${GH_REF} -b ${P_BRANCH} tmpdir
  - cp -r tmpdir/.git pasteme
  - cp nginx.conf LICENSE DEPLOY.md pasteme
  - cd pasteme
  - rm css/*.css js/*.js
  - mv DEPLOY.md README.md
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add --all
  - git commit -m "build from travis-ci `TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S'`"
  - git push https://${GH_TOKEN}@${GH_REF} ${P_BRANCH}
  - echo 'Start updating PasteMe dev'
  - git clone https://github.com/LucienShui/PasteMe.git -b dev PasteMeDev --recursive
  - cd PasteMeDev
  - git submodule foreach git pull origin master
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add --all
  - git commit -m "push from travis-ci `TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S'`"
  - git push https://${GH_TOKEN}@${GH_PASTEME} dev

branches:
  only:
    - master

notifications:
  email:
    - lucien@lucien.ink
  on_failure: always

env:
  global:
    - GH_REF: github.com/LucienShui/PasteMeFrontend.git
    - GH_PASTEME: github.com/LucienShui/PasteMe.git
    - P_BRANCH: build

addons:
  hosts:
    - ${WEBHOOK}
